### ISSUE TITLE
Extracting SDK

### ISSUE THREAD

**Issue by d3ibis** [MattrAus/iOS-Tweak-Development-for-Windows#6]
Dear, whenever I'm running this command (tar xvf iPhoneOSX.X.sdk.zip)

I'm getting these errors:

- tar: This does not look like a tar archive
- tar: Skipping to next header
- tar: Exiting with failure status due to previous errors

My command is: **tar xvf iPhoneOS11.1.sdk.zip**

if I change extension, will it work ?

ThanQ in advance...

**Comment by MattrAus** [comment]
I just looked into this, and have since updated the guide.
Please begin your install from the [Install apt-cyg](https://github.com/MattrAus/iOS-Tweak-Development-for-Windows#install-apt-cyg) 

Check commit [5ee87f080f0e68aa24d74d4fd02cd8ef7cdbd95e](https://github.com/MattrAus/iOS-Tweak-Development-for-Windows/commit/5ee87f080f0e68aa24d74d4fd02cd8ef7cdbd95e) for more information
